\c jewelry_dev

INSERT INTO bracelets (name, image, description, details, price) VALUES
('Arctic Gleam', 'https://i.ibb.co/S5qrX4g/arctic-gleam.jpg', 'The Arctic Gleam tennis bracelet is a celebration of refined elegance. Featuring a continuous row of radiant round-cut diamonds set in polished platinum, it’s the perfect piece for elevating any outfit with effortless sophistication.', ARRAY['Platinum setting', 'Round-cut diamonds', 'Length: 7.5 inches', 'Designed for everyday luxury', 'Product number: 70183001'], '$10,200'),
('Blue Horizon', 'https://i.ibb.co/qM7XBXv/blue-horizon.jpg', 'The Blue Horizon bracelet redefines elegance with its sleek and modern design. Featuring a delicate white gold bangle adorned with round-cut sapphires and sparkling diamonds in a refined pattern, this bracelet exudes understated luxury. Its versatile style transitions effortlessly from day to evening, adding a touch of sophistication to every look.', ARRAY['18k white gold', 'Round-cut sapphires and diamonds', 'Diameter: 6.5 inches', 'Crafted for durability and comfort', 'Product number: 70183913'], '$12,000'),
('Ruby Reverie', 'https://i.ibb.co/4WwZcHc/ruby-reverie.jpg', 'The Ruby Reverie bracelet is a captivating blend of timeless elegance and bold sophistication. Featuring alternating oval-cut rubies and dazzling diamonds set in warm yellow gold, this bracelet embodies the perfect balance of luxury and charm. Its striking design evokes passion and confidence, making it a stunning statement piece for any occasion.', ARRAY['18k yellow gold', 'Alternating oval-cut rubies and round diamonds', 'Length: 7 inches', 'Designed for comfort and secure wear', 'Product number: 70183912'], '$39,000');

INSERT INTO earrings (name, image, description, details, price) VALUES
('Azure Hoops', 'https://i.ibb.co/DW5FWQ5/azure-hoops.jpg', 'The Azure Hoops earrings bring a modern twist to timeless elegance. Featuring round-cut sapphires set along the outer edge of polished white gold hoops, they deliver a bold yet refined look, perfect for any occasion.', ARRAY['18k white gold', 'Round-cut sapphires', 'Diameter: 1.5 inches', 'Hinged closure for easy wear', 'Product number: 90113004'], '$925'),
('Icy Cascade', 'https://i.ibb.co/TYJRVXg/icy-cascade.jpg', 'The Icy Cascade earrings radiate elegance and sophistication. With teardrop-shaped diamonds suspended from round-cut diamonds, this platinum set exudes brilliance and timeless charm, making it perfect for any special occasion.', ARRAY['Platinum setting', 'Teardrop and round-cut diamonds', 'Drop length: 2 inches', 'Designed for secure wear', 'Product number: 90113001'], '$7,200'),
('Ruby Flame', 'https://i.ibb.co/wc3ryMQ/ruby-flame.jpg', 'The Ruby Flame earrings are a fiery celebration of passion and elegance. Featuring bold round-cut rubies in a classic yellow gold stud setting, these earrings make a striking yet versatile statement.', ARRAY['18k yellow gold', 'Round-cut rubies', 'Stud design', 'Diameter: 6mm', 'Product number: 90113002'], '$1,075');

INSERT INTO necklaces (name, image, description, details, price) VALUES
('Crimson Heart', 'https://i.ibb.co/WxHzpdr/crimson-heart.jpg', 'The Crimson Heart necklace captures the essence of passion and love. A heart-shaped ruby is encased in yellow gold, accented by sparkling diamonds for a design that radiates warmth and romance.', ARRAY['18k yellow gold', 'Heart-shaped ruby pendant', 'Diamond accents', 'Length: 18 inches', 'Product number: 70174003'], '$16,500'),
('Frostfall', 'https://i.ibb.co/Rb4ybT2/DALL-E-2025-01-06-14-01-30-A-centered-catalog-style-image-of-a-luxurious-platinum-necklace-featuring.jpg', 'The Frostfall necklace is a symbol of serene beauty. A single, brilliant pear-shaped diamond is suspended on a polished platinum chain, creating an understated yet dazzling look that’s ideal for every occasion.', ARRAY['Platinum chain', 'Pear-shaped diamond pendant', 'Length: 16 inches', 'Designed for timeless wear', 'Product number: 70174002'], '$950'),
('Celestial Lagoon', 'https://i.ibb.co/rZTVHFK/midnight-glimmer.jpg', 'The Celestial Lagoon necklace exudes ethereal beauty. Featuring a vibrant blue topaz pendant framed by a shimmering halo of pavé diamonds, it is set in white gold and suspended from a delicate chain. This piece captures the serene elegance of a starlit evening.', ARRAY['18k white gold', 'Blue topaz pendant', 'Pavé diamond halo', 'Length: 18 inches', 'Product number: 70174001'], '$20,500');

INSERT INTO rings (name, image, description, details, price) VALUES
('Blush Radiance', 'https://i.ibb.co/ZRsPSrc/blush-radiance.jpg', 'The Blush Radiance ring is a vision of delicate luxury. Crafted from rose gold, it features a radiant morganite center stone surrounded by a halo of sparkling diamonds. This design embodies romance and elegance, making it the perfect piece for any memorable occasion.', ARRAY['18k rose gold', 'Round-cut morganite center stone', 'Diamond halo and band accents', 'Available in sizes 5-9', 'Product number: 60154001'], '$2,700'),
('Emerald Flame', 'https://i.ibb.co/dM484TB/emerald-flame.jpg', 'The Emerald Flame ring is a bold masterpiece that captures attention. Featuring a vibrant emerald-cut emerald framed by two baguette-cut diamonds, it is set in polished yellow gold for a design that exudes luxury and sophistication.', ARRAY['18k yellow gold', 'Emerald-cut emerald center stone', 'Baguette-cut diamond accents', 'Available in sizes 5-9', 'Product number: 60154002'], '$10,900'),
('Frostfire Halo', 'https://i.ibb.co/xX7x8TJ/frostfire-halo.jpg', 'The Frostfire Halo ring dazzles with icy brilliance. A round-cut diamond takes center stage, surrounded by a fiery halo of smaller diamonds set in sleek platinum. This breathtaking design perfectly balances boldness with grace.', ARRAY['Platinum setting', 'Round-cut diamond center stone', 'Diamond halo and band accents', 'Available in sizes 5-9', 'Product number: 60154003'], '$2,000');

INSERT INTO watches (name, image, description, details, price) VALUES
('Titanium Twilight', 'https://i.ibb.co/7rNzcpQ/titanium-twilight.jpg', 'The Titanium Twilight watch combines contemporary design with enduring craftsmanship. Its titanium case and mesh band complement the minimalist navy blue dial, creating a bold yet understated look that suits any style.', ARRAY['Titanium case and mesh band', 'Navy blue dial with silver hour markers', 'Water-resistant up to 50m', 'Quartz movement', 'Product number: 80112003'], '$3,800'),
('Midnight Precision', 'https://i.ibb.co/w7vSY9L/midnight-precision.jpg', 'The Midnight Precision watch is a statement of modern sophistication and technical excellence. Featuring a sleek black dial, stainless steel case, and minimalist silver hour markers, this timepiece embodies timeless style. Designed for those who value precision and elegance, it’s perfect for any occasion.', ARRAY['Stainless steel case and band', 'Black dial with silver hour markers', 'Date window feature', 'Quartz movement', 'Product number: 80112001'], '$6,400'),
('Rose Quartz Elegance', 'https://i.ibb.co/YTk8P5P/rose-quartz-elegance.jpg', 'The Rose Quartz Elegance watch offers a touch of femininity and luxury. With its rose gold case, pearl-white dial, and diamond accents, this timepiece is both delicate and dazzling. The perfect blend of sophistication and practicality, it’s ideal for the modern woman.', ARRAY['Rose gold case and band', 'Pearl-white dial with diamond markers', 'Quartz movement', 'Diameter: 32mm', 'Product number: 80112002'], '$3,400');
