
INSERT INTO bracelets (name, image, description, details, price) VALUES
('Vine Hinged Bangle', 'https://i.ibb.co/z6PxxMj/bangle1.jpg', 'Inspired by the natural world, Tiffany Victoria designs capture the fluid movement of flowers, vines and leaves with a mix of expertly cut diamonds. This hinged bangle is crafted of 18k gold that features a contrast of high polish and sandblasted finishes. Round brilliant diamonds set in an alternating pattern play off the light and accentuate the vine motif. When too many diamonds are never enough, Tiffany Victoria is the ultimate way to shine. Wear this bangle on its own or paired with your favorite diamond tennis bracelet for sparkle you can’t ignore.', ARRAY['18k yellow gold with round brilliant diamonds', 'Size medium', 'Fits wrists up to 6.25"', 'Carat total weight .46', 'Product number:69524346'], '$10,200'),
('X Closed Narrow Hinged Bangle', 'https://i.ibb.co/gV6t8DV/bangle2.jpg', 'Traced with over 100 round brilliant diamonds, this closed hinged bangle is designed with an iconic knife edge profile, a Tiffany code of the house since the introduction of the Tiffany® Setting engagement ring in 1886. Wearable emblems inspired by the Roman numerals on the iconic clock at the New York flagship store, the Atlas X collection is a reminder to take time into your own hands and treasure what matters most. Pair this narrow bangle with other Tiffany bracelets, with or without diamonds, for a strong style statement.', ARRAY['18k rose gold with over 100 round brilliant diamonds', 'Size medium', 'Fits wrists up to 6.25"', 'Carat total weight .33', 'Product number:68174147'], '$12,000'),
('36 Stone Bracelet', 'https://i.ibb.co/dLrhCzn/tiffany-co-schlumberger36-stone-bracelet-15149582-1041715-ED.webp', 'Jean Schlumberger’s visionary creations are among the world’s most intricate designs. Blazing with diamonds, this striking bracelet makes a dazzling statement.', ARRAY['18k gold and platinum with round brilliant diamonds', 'Carat total weight 2.95', 'Product number: 60108488'], '$39,000');

INSERT INTO earrings (name, image, description, details, price) VALUES
('Olive Leaf Climber Earrings', 'https://i.ibb.co/KmSD0kZ/paloma-picassoolive-leaf-climber-earrings-60702551-1026018-ED.webp', 'Inspired by the olive branch, a symbol of peace and abundance.', ARRAY['18k gold', 'Original designs copyrighted by Paloma Picasso', 'Product number: 60702543'], '$925'),
('Tiffany Soleste® Earrings', 'https://i.ibb.co/Wg9nnrQ/tiffany-solesteearrings-37514594-1026002-ED.webp', 'Earrings in platinum with round aquamarines and round brilliant diamonds. Aquamarines, 6 mm.', ARRAY['Product number: 60005214'], '$7,200'),
('Open Heart Stud Earrings', 'https://i.ibb.co/824xr27/elsa-perettiopen-heart-stud-earrings-12318936-933797-ED.webp', 'The simple, evocative shape of Elsa Peretti Open Heart designs celebrates the spirit of love. Sweeping lines and open spaces form this elegant creation.', ARRAY['18k gold', '11 mm wide', 'Original designs copyrighted by Elsa Peretti', 'Product number: 60018073'], '$1,075');

INSERT INTO necklaces (name, image, description, details, price) VALUES
('Graduated Link Necklace', 'https://i.ibb.co/PQS2cZb/tiffany-hardweargraduated-link-necklace-38086766-1025207-ED.webp', 'Tiffany HardWear is elegantly subversive and captures the spirit of the women of New York City. A bold, graduated chain of gauge links captures the urban edge of the city, making a stunning statement.', ARRAY['18k gold', '18" long', 'Designed to be comfortable and easy to wear', 'Product number: 60153063'], '$16,500'),
('Diamonds by the Yard® Single Diamond Pendant', 'https://i.ibb.co/TY2xgjY/elsa-perettidiamonds-by-the-yard-single-diamond-pendant-10769213-1031666-ED.webp', 'A single hand-polished diamond shines at the center of this delicate and refined 18k yellow gold pendant. Elsa Peretti’s revolutionary Diamonds by the Yard® collection features a combination of fine, fluid chains and bezel-set stones that forever changed the role of diamonds in fashion. Suspended like a single drop of light against the skin, layer this design with other Diamonds by the Yard® pendants and necklaces of varying lengths and metals for a look that’s all your own.', ARRAY['18k yellow gold with a bezel-set round brilliant diamond', 'On a 16" cable chain', 'Spring clasp closure', 'Carat weight .05', 'Original designs copyrighted by Elsa Peretti', 'Product number: 60017719'], '$950'),
('Snake Necklace', 'https://i.ibb.co/HVtTq3z/elsa-perettisnake-necklace-11951929-1034727-ED.webp', 'The serpentine form carries streamlined modernity. Necklace in 18k gold. 20" long. Original designs copyrighted by Elsa Peretti.', ARRAY['Product number: 60116249'], '$20,500');

INSERT INTO rings (name, image, description, details, price) VALUES
('V Ring', 'https://imagizer.imageshack.com/img924/821/kGr1oF.jpg', 'Designed to nest with your Tiffany engagement ring, Tiffany Soleste V is crafted with clean lines and a slim silhouette that make it perfect for stacking. Scintillating diamonds are hand set in this elegant band.', ARRAY['18k gold with round brilliant diamonds', 'Carat total weight .17', 'Product number: 60876282'], '$2,700'),
('Sixteen Stone Ring', 'https://imagizer.imageshack.com/img924/1047/US21GX.jpg', 'Jean Schlumberger’s visionary creations are among the world’s most intricate designs. Brilliant diamonds and rubies alternate with graphic X''s to create this dazzling ring.', ARRAY['18k gold and platinum', 'Round rubies, carat total weight .65', 'Round brilliant diamonds, carat total weight .57', 'Product number: 60696799'], '$10,900'),
('Band Ring', 'https://imagizer.imageshack.com/img924/5108/cjBvdn.jpg', 'Designed with intricate beveled edges, this band ring is the perfect complement to a Tiffany True engagement ring. Wear one ring as a wedding band or two stacked together for a bold look.', ARRAY['Platinum', '4 mm wide', 'Product number: 68651921'], '$2,000');

INSERT INTO watches (name, image, description, details, price) VALUES
('Makers 16 mm Square Watch','https://imagizer.imageshack.com/img922/2747/gEwEnc.jpg', 'The Tiffany 1837 Makers watch collection blends artful design, luxurious materials and thoughtful craftsmanship to create a distinctly modern timepiece. The latest iteration of the Tiffany 1837 Makers watch, this 16 mm square watch is complemented with a stunning pink mother-of-pearl dial and diamond indexes.', ARRAY['Stainless steel with a pink mother-of-pearl dial and diamond indexes', '16 x 16 mm case', 'Carat total weight .14', 'Quartz movement', 'Water resistant to 50 meters/160 feet/5 ATM', 'Swiss-made', 'Product number: 69345638'], '$3,800'),
('2-Hand 24 mm Watch', 'https://imagizer.imageshack.com/img923/2698/oTt9Mn.jpg', 'Inspired by the clean lines of the Roman numerals in the clock above the entrance at the Tiffany Fifth Avenue flagship store, the Atlas® watch collection combines graphic clarity with functional elegance for pieces that are easy to wear every day. A modern iteration of strong and elemental design, this 24 mm round watch is designed in stainless steel with refined diamond accents and a pink mother-of-pearl dial.', ARRAY['Stainless steel with round brilliant diamonds', 'Pink mother-of-pearl dial', '24 mm case', 'Carat total weight .28', 'Quartz movement', 'Water resistant to 30 meters/100 feet/3 ATM', 'Swiss-made', 'Product number: 69291600'], '$6,400'),
('3-Hand 40 mm Watch', 'https://imagizer.imageshack.com/img923/3179/ol8Qhl.jpg', 'Men''s watch in stainless steel. Blue soleil dial features gold poudré numerals. On a blue alligator strap. 40 mm case. Self-winding mechanical movement. Power reserve 42 hours. Water resistant to 100 meters/330 feet/10 ATM. Swiss-made.', ARRAY['Product number: 60166343'], '$3,400');
